# docker-build.yml in .github/workflows/
name: Build and Push Docker Image to GHCR

# Workflow will run when a push to main branch occurs
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout/download the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: print variables
        run: |
            echo ${{ github.repository }}
            echo ${{ github.actor }}
            echo ${{ github.sha }}
            echo ${{ github.ref }}
            echo ${{ github.event_name }}
            echo ${{ github.event }}

      # Step 3: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Extract Docker metadata (tags, labels, etc.)
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/my-app
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest
            type=raw,value=sha-{{short-sha}}
            type=raw,value=branch-{{branch}}
            type=raw,value=sha-full-{{sha}}

      # Step 5: Build and push Docker image to GHCR
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
